### ISSUE TITLE
Disappearing cursor and freezing video on some fullscreen applications

### ISSUE THREAD

**Issue by Soveu** [fzwoch/obs-gnome-screencast#23]
For example recording alacritty or other terminals on fullscreen is fine, while games (like factorio or minecraft) on preview and recording are frozen and cursor disappears when playing

Focusing back on OBS window un-freezes recording

It only happens when game is on screen that is being captured

System: Fedora 33, Ryzen 2500U

Edit: Could it be issue with XWayland?

**Comment by fzwoch** [comment]
Could be an issue with XWayland or GNOME, or their combined interaction.

This plugin is rather simple. It doesn't do anything with the cursor for example other than telling the Mutter API to capture the cursor too. So all it does is initiating the screen capture sessions and passes the delivered images from the capture into OBS.

It could be related to full screen modes where due to latency and efficiency they may get rendered differently - e.g. not though the compositor. In that case the screen cast API may not issue a redraw. But that's really entirely up to GNOME.

**Comment by fzwoch** [comment]
Closing as most likely something realted to other components, but not this pugin.
