### ISSUE TITLE
Put the installation location for this plugin in the readme

### ISSUE THREAD

**Issue by osirase** [fzwoch/obs-gnome-screencast#3]
Hiya,

I spent about 3 days on an off trying to figure out where to put gnome-screencast.so. I finally found it because of a snippet scrapped from google:

https://imgur.com/ajYFqkO

Having /usr/local/lib/obs-plugins somewhere in the readme would be wonderful.

**Comment by fzwoch** [comment]
Google is actually indexing the README here:

```
# optional; for installing the plugin into
# '/usr/local/lib/obs-plugins'

$ sudo ninja -C build install
```

I'm not more specific here because honestly I'm not sure. `/usr/local/lib/obs-plugins` works when you have compiled OBS yourself. I think the path is different when you install it via package manager or snap. Also I think there are user paths that work too. It is more like "install it into a valid OBS plugin path - whatever that is (check your OBS documentation)".

**Comment by osirase** [comment]
Ah okay I see, for context I had installed obs via dnf on Fedora using the rpmfusion repo.

**Comment by fzwoch** [comment]
If you have more detailed insight or suggestions on how to improve it just let me know ;-)

**Comment by different55** [comment]
In case any Debian users are lost, it's `/usr/lib/x86_64-linux-gnu/obs-plugins`.

**Comment by bocekm** [comment]
On Fedora 31, the plugin does not show up in OBS when put to /usr/local/lib/obs-plugins and there's no folder /usr/lib/x86_64-linux-gnu/. I couldn't figure out how to use the plugin.

**Comment by fzwoch** [comment]
There are just too many ways to install/compile OBS and each of them have their own preferred plugin directories. I really don't know them all. But I have seen these questions pop up regularly. Since this is not plugin specific - perhaps this is worth for a Wiki entry on the OBS repository itself. (If someone figures out all the path behaviors..)
